---

- name: Assert vars and install openvpn packages
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Display Variable
      debug: msg="{{ group_names|join(" ") }}"

    - name: Install openvpn packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      vars:
        - group_name: "{{ group_names|join(' ') }}"
      with_items: "{{ openvpn_packages[group_name] }}"


- name: Setup openvpn server
  hosts: vpn_server
  vars_files:
    - vars/main.yml

  roles:
    - OpenVPN_server
