---

- name: Ensure /etc/openvpn/easy-rsa (Public Key Infrastructure directory) exists
  ansible.builtin.file:
    path: /etc/openvpn/easy-rsa
    state: directory
    mode: "0755"

- name: Generate Public Key Infrastructure
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa init-pki"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki

- name: Generate certificate authority (CA)
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa build-ca nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/ca.crt
  environment:
    EASYRSA_BATCH: "yes"
    KEY_NAME: "server"
    KEY_COUNTRY: "{{ openvpn_vars['key_country'] }}"
    KEY_PROVINCE: "{{ openvpn_vars['key_province'] }}"
    KEY_CITY: "{{ openvpn_vars['key_city'] }}"
    KEY_ORG: "{{ openvpn_vars['key_org'] }}"
    KEY_EMAIL: "{{ openvpn_vars['key_email'] }}"
    KEY_OU: "{{ openvpn_vars['key_ou'] }}"

- name: Easyrsa gen-dh
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa gen-dh"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/dh.pem

- name: Easyrsa build-server-full server nopass
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa build-server-full server nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/server.crt

- name: Generate Certificate Revocation List (CRL)
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa gen-crl"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/crl.pem

- name: Openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
  ansible.builtin.command:
    cmd: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
    creates: /etc/openvpn/easy-rsa/pki/ta.key

- name: Copy files to /etc/openvpn/server
  ansible.builtin.copy:
    src: /etc/openvpn/easy-rsa/pki/{{ item }}
    dest: /etc/openvpn/server/{{ item | basename }}
    mode: "0640"
    remote_src: yes
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - issued/server.crt
    - private/server.key
    - private/ca.key

- name: Copy files to /etc/openvpn
  ansible.builtin.copy:
    src: /etc/openvpn/easy-rsa/pki/{{ item }}
    dest: /etc/openvpn/{{ item | basename }}
    mode: "0640"
    remote_src: yes
  loop:
    - ca.crt
    - ta.key

- name: Place server.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ openvpn_configuration_directory }}/server.conf"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  notify:
    - restart openvpn

- name: Place client.conf
  ansible.builtin.template:
    src: client.conf.j2
    dest: "{{ openvpn_configuration_directory }}/client.conf"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  notify:
    - restart openvpn

- name: Copy certificates to the client folder and create ovpn file
  include_tasks: inner.yml
  with_items: "{{ groups['vpn_clients'] }}"
  loop_control:
    loop_var: vpn_client

- name: Fetch ovpn file
  fetch:
    src: "/etc/openvpn/client/{{ hostvars[item].client_name }}.ovpn"
    dest: "{{ destination_key }}/"
    flat: yes
  with_items:
    - "{{ groups['vpn_clients'] }}"